### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/dsci-532_group_02#26]
Hey Group 2,

Congrats on completing Milestone 1! Seems you're already building a solid foundation. Your proposal does well touching on all the core concepts and your dataset and purpose independently seem solid (although be careful with grammar and run-on sentences!). I would note that it may be useful to look only at *lightness* or *brightness* and not both (cf. HSL vs HSB/HSV). I think the research questions you pose are also reasonable, though the usage scenario is rather long-winded and a bit unclear. It would have been better to focus this section on the broader usage scenario without focusing so much on the specifics. I do also wonder if this dashboard may actually make more sense for a consumer than for a company though.

With regards to your dashboard:
- I think it looks quite useful. Everything is quite clearly presented and it seems it should be rather user friendly at the same time
- It presents most relevant info with a good level of complexity for milestone 2. If you have time to expand it in the future, perhaps you could consider the ability to toggle between distributions of H, S, and L (or V)
- It might also be interesting to make the HSV rangesliders draw a bounding box over some projected HSV chart (a chart like you'd see in a typical color picker)

**Comment by KangboLu** [comment]
Yes, in fact, in milestone 2, we only looked at lightness. Lightness is a composite score of HSV that conveys how light or dark a shade is perceived by a human. We are using lightness values for the two histograms because we thought it would relay more information simultaneously than a toggle for each of the H, S, and V values. We also included usage tutorials in our README for milestone 2 to make it more friendly. We didn't implement a color picker because the common color range for foundations is limited and it doesn't fit well using a traditional color picker with a very wide range of colors. Thanks for the feedback.
